version: '3'
services:
  # app:
  #   container_name: full_app
  #   build: .
  #   ports: 
  #     - 8080:8080 
  #   restart: on-failure
  #   # volumes:
  #   #   - api:/var/www/html
  #   depends_on:
  #     - fullstack-postgres          # Uncomment this when using postgres.

  fullstack-postgres:
    image: postgres:latest
    container_name: full_db_postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=passowrd
      - POSTGRES_DB=postgres
      - DATABASE_HOST=localhost
    ports:
      - '5432:5432'
    # volumes:
    #   - database_postgres:/var/lib/postgresql/data
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin_container
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
  #   depends_on:
  #     - fullstack-postgres
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - fullstack
  #   restart: unless-stopped